// ============================================================
// spendingIntelligence.ts
// Spending Intelligence Engine - Finanzas GC
// Behavioral analysis, pattern detection, wasteful spending
// identification, and spending optimization insights
// ============================================================

export interface SpendingTransaction {
  id?: string
    date: string               // ISO date string
      merchant: string
        normalizedMerchant: string
          category: string
            amount: number
              isEssential: boolean
                month: string              // YYYY-MM
                }

                export interface MerchantPattern {
                  merchant: string
                    category: string
                      totalSpent: number
                        transactionCount: number
                          averageAmount: number
                            frequency: 'daily' | 'weekly' | 'monthly' | 'sporadic'
                              isSubscription: boolean
                              }

                              export interface SpendingInsight {
                                type: 'waste' | 'pattern' | 'optimization' | 'anomaly' | 'positive'
                                  severity: 'high' | 'medium' | 'low'
                                    title: string
                                      description: string
                                        potentialSavings?: number
                                          merchant?: string
                                            category?: string
                                            }

                                            export interface SpendingIntelligenceResult {
                                              totalSpent: number
                                                essentialSpent: number
                                                  discretionarySpent: number
                                                    essentialRatio: number
                                                      topCategories: Array<{ category: string; total: number; percent: number }>
                                                        topMerchants: MerchantPattern[]
                                                          subscriptions: MerchantPattern[]
                                                            insights: SpendingInsight[]
                                                              monthOverMonthChange: number   // % change from previous month
                                                                spendingVelocity: number       // daily avg spend
                                                                }

                                                                // ── Frequency Detection ──────────────────────────────────────
                                                                function detectFrequency(transactions: SpendingTransaction[]): MerchantPattern['frequency'] {
                                                                  if (transactions.length < 2) return 'sporadic'
                                                                    const sorted = [...transactions].sort((a, b) => a.date.localeCompare(b.date))
                                                                      const intervals: number[] = []
                                                                        for (let i = 1; i < sorted.length; i++) {
                                                                            const d1 = new Date(sorted[i - 1].date).getTime()
                                                                                const d2 = new Date(sorted[i].date).getTime()
                                                                                    intervals.push((d2 - d1) / (1000 * 60 * 60 * 24)) // days
                                                                                      }
                                                                                        const avgInterval = intervals.reduce((s, i) => s + i, 0) / intervals.length
                                                                                          if (avgInterval <= 2) return 'daily'
                                                                                            if (avgInterval <= 10) return 'weekly'
                                                                                              if (avgInterval <= 35) return 'monthly'
                                                                                                return 'sporadic'
                                                                                                }

                                                                                                // ── Subscription Detection ───────────────────────────────────
                                                                                                const KNOWN_SUBSCRIPTIONS = [
                                                                                                  'NETFLIX', 'SPOTIFY', 'AMAZON', 'YOUTUBE', 'DISNEY', 'HBO',
                                                                                                    'APPLE', 'GOOGLE', 'MICROSOFT', 'OPENAI', 'CANVA', 'DROPBOX',
                                                                                                      'ZOOM', 'SLACK', 'NOTION', 'FIGMA', 'GITHUB', 'CHATGPT',
                                                                                                      ]
                                                                                                      
                                                                                                      function isLikelySubscription(merchant: string, frequency: string, transactions: SpendingTransaction[]): boolean {
                                                                                                        const upper = merchant.toUpperCase()
                                                                                                          if (KNOWN_SUBSCRIPTIONS.some((s) => upper.includes(s))) return true
                                                                                                            if (frequency === 'monthly' && transactions.length >= 2) {
                                                                                                                const amounts = transactions.map((t) => t.amount)
                                                                                                                    const allSameAmount = amounts.every((a) => Math.abs(a - amounts[0]) < 2)
                                                                                                                        if (allSameAmount) return true
                                                                                                                          }
                                                                                                                            return false
                                                                                                                            }
                                                                                                                            
                                                                                                                            // ── Merchant Pattern Analysis ────────────────────────────────
                                                                                                                            export function analyzeMerchantPatterns(transactions: SpendingTransaction[]): MerchantPattern[] {
                                                                                                                              const merchantMap: Record<string, SpendingTransaction[]> = {}
                                                                                                                              
                                                                                                                                for (const tx of transactions) {
                                                                                                                                    const key = tx.normalizedMerchant || tx.merchant
                                                                                                                                        if (!merchantMap[key]) merchantMap[key] = []
                                                                                                                                            merchantMap[key].push(tx)
                                                                                                                                              }
                                                                                                                                              
                                                                                                                                                return Object.entries(merchantMap)
                                                                                                                                                    .map(([merchant, txs]) => {
                                                                                                                                                          const totalSpent = txs.reduce((s, t) => s + t.amount, 0)
                                                                                                                                                                const frequency = detectFrequency(txs)
                                                                                                                                                                      return {
                                                                                                                                                                              merchant,
                                                                                                                                                                                      category: txs[0].category,
                                                                                                                                                                                              totalSpent,
                                                                                                                                                                                                      transactionCount: txs.length,
                                                                                                                                                                                                              averageAmount: totalSpent / txs.length,
                                                                                                                                                                                                                      frequency,
                                                                                                                                                                                                                              isSubscription: isLikelySubscription(merchant, frequency, txs),
                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                        })
                                                                                                                                                                                                                                            .sort((a, b) => b.totalSpent - a.totalSpent)
                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                            // ── Spending Insights Generator ──────────────────────────────
                                                                                                                                                                                                                                            export function generateSpendingInsights(
                                                                                                                                                                                                                                              transactions: SpendingTransaction[],
                                                                                                                                                                                                                                                monthlyIncome?: number
                                                                                                                                                                                                                                                ): SpendingInsight[] {
                                                                                                                                                                                                                                                  const insights: SpendingInsight[] = []
                                                                                                                                                                                                                                                    const patterns = analyzeMerchantPatterns(transactions)
                                                                                                                                                                                                                                                      const totalSpent = transactions.reduce((s, t) => s + t.amount, 0)
                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                        // 1. High discretionary spending
                                                                                                                                                                                                                                                          const discretionary = transactions.filter((t) => !t.isEssential)
                                                                                                                                                                                                                                                            const discretionaryTotal = discretionary.reduce((s, t) => s + t.amount, 0)
                                                                                                                                                                                                                                                              const discRatio = totalSpent > 0 ? discretionaryTotal / totalSpent : 0
                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                if (discRatio > 0.5) {
                                                                                                                                                                                                                                                                    insights.push({
                                                                                                                                                                                                                                                                          type: 'waste',
                                                                                                                                                                                                                                                                                severity: discRatio > 0.7 ? 'high' : 'medium',
                                                                                                                                                                                                                                                                                      title: 'Alto gasto discrecional',
                                                                                                                                                                                                                                                                                            description: `${(discRatio * 100).toFixed(0)}% del gasto es no esencial. Revisa categorías de entretenimiento y compras.`,
                                                                                                                                                                                                                                                                                                  potentialSavings: Math.round(discretionaryTotal * 0.2),
                                                                                                                                                                                                                                                                                                        category: 'Discretionary',
                                                                                                                                                                                                                                                                                                            })
                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                // 2. Subscriptions audit
                                                                                                                                                                                                                                                                                                                  const subscriptions = patterns.filter((p) => p.isSubscription)
                                                                                                                                                                                                                                                                                                                    const subscriptionTotal = subscriptions.reduce((s, p) => s + p.totalSpent, 0)
                                                                                                                                                                                                                                                                                                                      if (subscriptions.length > 5) {
                                                                                                                                                                                                                                                                                                                          insights.push({
                                                                                                                                                                                                                                                                                                                                type: 'optimization',
                                                                                                                                                                                                                                                                                                                                      severity: 'medium',
                                                                                                                                                                                                                                                                                                                                            title: `${subscriptions.length} suscripciones activas detectadas`,
                                                                                                                                                                                                                                                                                                                                                  description: `Gasto mensual en suscripciones: S/ ${subscriptionTotal.toFixed(0)}. Revisa cuáles realmente usas.`,
                                                                                                                                                                                                                                                                                                                                                        potentialSavings: Math.round(subscriptionTotal * 0.3),
                                                                                                                                                                                                                                                                                                                                                              category: 'Subscriptions',
                                                                                                                                                                                                                                                                                                                                                                  })
                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                      // 3. High single-merchant concentration
                                                                                                                                                                                                                                                                                                                                                                        if (patterns.length > 0) {
                                                                                                                                                                                                                                                                                                                                                                            const topMerchant = patterns[0]
                                                                                                                                                                                                                                                                                                                                                                                const topRatio = totalSpent > 0 ? topMerchant.totalSpent / totalSpent : 0
                                                                                                                                                                                                                                                                                                                                                                                    if (topRatio > 0.25) {
                                                                                                                                                                                                                                                                                                                                                                                          insights.push({
                                                                                                                                                                                                                                                                                                                                                                                                  type: 'pattern',
                                                                                                                                                                                                                                                                                                                                                                                                          severity: 'medium',
                                                                                                                                                                                                                                                                                                                                                                                                                  title: `Concentración alta en ${topMerchant.merchant}`,
                                                                                                                                                                                                                                                                                                                                                                                                                          description: `${(topRatio * 100).toFixed(0)}% del gasto va a un solo comercio. Considera diversificar.`,
                                                                                                                                                                                                                                                                                                                                                                                                                                  merchant: topMerchant.merchant,
                                                                                                                                                                                                                                                                                                                                                                                                                                          potentialSavings: Math.round(topMerchant.totalSpent * 0.1),
                                                                                                                                                                                                                                                                                                                                                                                                                                                })
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                        // 4. Food delivery excess
                                                                                                                                                                                                                                                                                                                                                                                                                                                          const foodDelivery = transactions.filter((t) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              ['UBER', 'RAPPI', 'GLOVO', 'PEDIDOS'].some((app) => t.normalizedMerchant?.toUpperCase().includes(app))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const foodDeliveryTotal = foodDelivery.reduce((s, t) => s + t.amount, 0)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (foodDelivery.length > 8) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        insights.push({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              type: 'waste',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    severity: 'medium',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          title: 'Uso frecuente de delivery de comida',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                description: `${foodDelivery.length} pedidos de delivery por S/ ${foodDeliveryTotal.toFixed(0)}. Cocinar en casa ahorra hasta 60%.`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      potentialSavings: Math.round(foodDeliveryTotal * 0.5),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            category: 'Food',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // 5. Income ratio check
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (monthlyIncome && monthlyIncome > 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const spendingRatio = totalSpent / monthlyIncome
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (spendingRatio > 0.9) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    insights.push({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type: 'anomaly',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    severity: 'high',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            title: 'Gasto supera el 90% del ingreso',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    description: `Estás gastando S/ ${totalSpent.toFixed(0)} de S/ ${monthlyIncome.toFixed(0)} de ingreso. Margen de ahorro crítico.`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            potentialSavings: Math.round(totalSpent * 0.1),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } else if (spendingRatio < 0.6) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            insights.push({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    type: 'positive',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            severity: 'low',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    title: 'Excelente control de gastos',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            description: `Solo estás usando el ${(spendingRatio * 100).toFixed(0)}% de tu ingreso en gastos. ¡Buen trabajo!`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return insights.sort((a, b) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const severityOrder = { high: 0, medium: 1, low: 2 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return severityOrder[a.severity] - severityOrder[b.severity]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // ── Master Spending Intelligence ─────────────────────────────
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    export function analyzeSpending(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      transactions: SpendingTransaction[],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        previousMonthTransactions?: SpendingTransaction[],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          monthlyIncome?: number
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ): SpendingIntelligenceResult {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const totalSpent = transactions.reduce((s, t) => s + t.amount, 0)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const essentialSpent = transactions.filter((t) => t.isEssential).reduce((s, t) => s + t.amount, 0)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const discretionarySpent = totalSpent - essentialSpent
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const essentialRatio = totalSpent > 0 ? essentialSpent / totalSpent : 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Category breakdown
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const categoryMap: Record<string, number> = {}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for (const tx of transactions) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            categoryMap[tx.category] = (categoryMap[tx.category] ?? 0) + tx.amount
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const topCategories = Object.entries(categoryMap)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .map(([category, total]) => ({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          category,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                total,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      percent: totalSpent > 0 ? (total / totalSpent) * 100 : 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              .sort((a, b) => b.total - a.total)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  .slice(0, 8)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const patterns = analyzeMerchantPatterns(transactions)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const subscriptions = patterns.filter((p) => p.isSubscription)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const insights = generateSpendingInsights(transactions, monthlyIncome)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // Month-over-month change
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const prevTotal = previousMonthTransactions?.reduce((s, t) => s + t.amount, 0) ?? 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const monthOverMonthChange = prevTotal > 0 ? ((totalSpent - prevTotal) / prevTotal) * 100 : 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Spending velocity (per day - assume 30-day month)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const spendingVelocity = totalSpent / 30
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        totalSpent,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            essentialSpent,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                discretionarySpent,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    essentialRatio,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        topCategories,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            topMerchants: patterns.slice(0, 10),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                subscriptions,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    insights,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        monthOverMonthChange,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            spendingVelocity,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
